# Generated by Django 2.2.7 on 2019-11-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApiSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML/SOAP')], db_index=True, max_length=32, unique=True)),
                ('hasCertificate', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='.')),
                ('clientName', models.CharField(db_index=True, max_length=32, unique=True)),
                ('apiConnection', models.CharField(choices=[('CUSTOM_SOCKET', 'CUSTOM_SOCKET'), ('HTTP', 'HTTP(S)')], db_index=True, max_length=32, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ClientApiSetups',
                'verbose_name_plural': 'ClientApiSetups',
                'db_table': 'ClientApiSetups',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='requests',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='hasCertificate',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='isCustomSocket',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='isXml',
        ),
        migrations.AlterField(
            model_name='requests',
            name='requestDestinationClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClientApiSetup'),
        ),
        migrations.AlterUniqueTogether(
            name='payloadkeyrequestmapping',
            unique_together={('request', 'payloadkey', 'placeholder')},
        ),
        migrations.CreateModel(
            name='ClientStaticConfsPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClientApiSetup')),
            ],
            options={
                'verbose_name': 'clientstaticconfs',
                'verbose_name_plural': 'clientstaticconfs',
                'db_table': 'ClientStaticConfs',
                'managed': True,
                'unique_together': {('client', 'key', 'value')},
            },
        ),
    ]
